-- 11-genre_id_all_shows.sql
-- List all shows with their genre IDs, NULL if no genre
SELECT TV_SHOWS.TITLE, TV_SHOW_GENRES.GENRE_ID
FROM TV_SHOWS
LEFT JOIN TV_SHOW_GENRES
ON TV_SHOWS.ID = TV_SHOW_GENRES.TV_SHOW_ID
ORDER BY TV_SHOWS.TITLE ASC, TV_SHOW_GENRES.GENRE_ID ASC;
