-- 12-no_genre.sql
-- List all shows without a genre
SELECT TV_SHOWS.TITLE, TV_SHOW_GENRES.GENRE_ID
FROM TV_SHOWS
LEFT JOIN TV_SHOW_GENRES ON TV_SHOWS.ID = TV_SHOW_GENRES.SHOW_ID
WHERE TV_SHOW_GENRES.GENRE_ID IS NULL
ORDER BY TV_SHOWS.TITLE ASC, TV_SHOW_GENRES.GENRE_ID ASC;
