-- 13-count_shows_by_genre.sql
-- List all genres and the number of shows linked to each
SELECT TV_GENRES.NAME AS GENRE, COUNT(TV_SHOW_GENRES.SHOW_ID) AS NUMBER_OF_SHOWS
FROM TV_GENRES
JOIN TV_SHOW_GENRES ON TV_GENRES.ID = TV_SHOW_GENRES.GENRE_ID
GROUP BY TV_GENRES.NAME
HAVING NUMBER_OF_SHOWS > 0
ORDER BY NUMBER_OF_SHOWS DESC;
