-- 16-shows_by_genre.sql
-- List all shows and all genres linked to that show, NULL if no genre
SELECT TV_SHOWS.TITLE, TV_GENRES.NAME
FROM TV_SHOWS
LEFT JOIN TV_SHOW_GENRES ON TV_SHOWS.ID = TV_SHOW_GENRES.SHOW_ID
LEFT JOIN TV_GENRES ON TV_SHOW_GENRES.GENRE_ID = TV_GENRES.ID
ORDER BY TV_SHOWS.TITLE ASC, TV_GENRES.NAME ASC;
